Read Excel file
vaibhavjain3/ERStudioReleaseHelper pull request #2
Opened 2019-11-28 11:00 UTC by rajatbatra0803

Read Excel file and store all cell value in object

2019-11-29 06:20 UTC, vaibhavjain3 requested changes

2019-11-29 06:20 UTC, vaibhavjain3 commented on .gitignore
> +.idea/
Why this file has been checked-in?

2019-11-29 06:20 UTC, vaibhavjain3 commented on src/main/java/com/erstudio/ERStudioReleaseHelper.java
> +    private ChangeTSVersionNumber changeTSVersionNumber;
This is main launcher file.
Nothing but main function will be there in this file to launch application.

2019-11-29 06:20 UTC, vaibhavjain3 commented on src/main/java/com/erstudio/ERStudioReleaseHelper.java
> +    public void readExcel() {
Entire Read write excel operation has to be moved into separate file.

2019-11-29 06:20 UTC, vaibhavjain3 commented on src/main/java/com/erstudio/tsversionchange/ChangeTSVersionNumber.java
> +}
Why not getters setters?

2019-11-29 06:20 UTC, vaibhavjain3 commented on src/main/java/com/erstudio/tsversionchange/ReadExcel.java
> +                    //serial number
Either add comments to all cells or don't add to any.
I prefer, add to all of them.

2019-11-29 06:20 UTC, vaibhavjain3 commented on src/main/java/com/erstudio/tsversionchange/model/ExcelModel.java
> +    String StringToReplaceFormat;
Why variable name is starting with Capital S?

2019-11-29 06:20 UTC, vaibhavjain3 commented on src/main/java/com/erstudio/tsversionchange/ReadExcel.java
> +        workbook.close();
try catch finally.

2019-11-29 06:20 UTC, vaibhavjain3 commented on src/main/java/com/erstudio/tsversionchange/ChangeTSVersionNumber.java
> +    public void readExcel() throws IOException {
Is this is a entity class or a controller class.
What is readExcel function doing in entity class?

2019-11-29 06:24 UTC, vaibhavjain3 commented on src/main/java/com/erstudio/tsversionchange/model/ExcelModel.java
> +    String StringToReplaceFormat;
Also,
Make this variable as an object - VersionFormat. Create another class with members like major, minor....

2019-11-29 07:35 UTC, rajatbatra0803 commented on .gitignore
> +.idea/
Don't we need .gitignore file to be checked in ?

2019-11-29 13:52 UTC, vaibhavjain3 requested changes

2019-11-29 13:52 UTC, vaibhavjain3 commented on .gitignore
> +.idea/
Let's study the use of .gitignore file and post here.

2019-11-29 13:52 UTC, vaibhavjain3 commented on src/main/java/com/erstudio/ERSStudioReleaseHelperUI.java
> +
Why Extra line.

2019-11-29 13:52 UTC, vaibhavjain3 commented on src/main/java/com/erstudio/tsversionchange/model/ExcelModel.java
> +    String stringToReplaceFormat;
I believe I asked for creation of new file here. Please check older comments.

2019-12-02 07:30 UTC, vaibhavjain3 requested changes
Please review.

2019-12-02 07:30 UTC, vaibhavjain3 commented on CodingGuidelines.md
> -5. If any review comments come, perform step 3-4 again and resolve conversation. Same pull request will pick the changes.
why this file has been changed.
two points got missed from new file.

2019-12-02 07:30 UTC, vaibhavjain3 commented on src/main/java/com/erstudio/ERStudioReleaseHelper.java
> -
Why this line has been removed?

2019-12-02 07:30 UTC, vaibhavjain3 commented on src/main/java/com/erstudio/ERStudioReleaseHelper.java
> -
Why this line has been removed?

2019-12-02 07:30 UTC, vaibhavjain3 commented on src/main/java/com/erstudio/constants/Constants.java
> -
Why this line has been removed?

2019-12-02 07:30 UTC, vaibhavjain3 commented on src/main/java/com/erstudio/tsversionchange/ProcessExcel.java
> +            // workbook.close();
why this comment is here? Aren't we doing workbook.close in finally block already?

2019-12-02 07:30 UTC, vaibhavjain3 commented on src/main/java/com/erstudio/tsversionchange/ProcessExcel.java
> +
What is this extra line at the end?

2019-12-02 10:18 UTC, vaibhavjain3 approved these changes
Approved

2019-12-02 10:18 UTC, merged